# Generated by Django 4.1.2 on 2022-10-15 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_prettynum_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='moblie',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^1\\d{10}$', '手机号格式错误')], verbose_name='手机号'),
        ),
    ]
