# Generated by Django 4.1.2 on 2022-10-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='', verbose_name='Logo')),
            ],
        ),
    ]
