# Generated by Django 4.1.2 on 2022-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.FileField(max_length=128, upload_to='city/', verbose_name='Logo'),
        ),
    ]
