# Generated by Django 4.1.2 on 2022-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_city_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, verbose_name='城市名'),
        ),
    ]
